<MyWidget>:
    orientation:'horizontal'
    adaptive_height:True
    # adaptive_width:True
    # adaptive_size:True
    MDRaisedButton:
        text:'-'
        size_hint : .2,1
        on_release:root.decrease()
    MDTextFieldRect:
        id:myvalue
        text:'1'
        halign:'center'
        size_hint : .6,1
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    MDRaisedButton:
        text:'+'
        size_hint : .2,1
        on_release:root.increase()
